# Generated by Django 3.1 on 2020-08-20 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('deliveryMade', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=100)),
                ('dietaryRestrictions', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('deliveryMade', models.BooleanField(default=False)),
                ('foodItem', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('foodItems', models.ManyToManyField(to='hello.FoodItem')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.ManyToManyField(to='hello.Employee')),
                ('manager', models.ManyToManyField(to='hello.Manager')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.menu')),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.restaurant'),
        ),
        migrations.AddField(
            model_name='employee',
            name='foodItem',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello.fooditem'),
        ),
    ]
