# Generated by Django 2.1.4 on 2021-02-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_hash',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
