# Generated by Django 2.1.4 on 2021-01-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20210102_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pricePaid',
            field=models.FloatField(),
        ),
    ]
