# Generated by Django 2.1.4 on 2020-09-12 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20200905_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='authZeroID',
        ),
    ]
