# Generated by Django 2.1.4 on 2021-02-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20210223_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='picture_url',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='picture_url',
            field=models.CharField(max_length=250),
        ),
    ]
