# Generated by Django 2.1.4 on 2021-02-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20210223_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('menuItems', models.ManyToManyField(related_name='add_ins', to='hello.MenuItem')),
                ('orderItems', models.ManyToManyField(related_name='add_ins', to='hello.OrderItem')),
            ],
        ),
    ]
