# Generated by Django 2.1.4 on 2021-01-28 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_menuitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='hello.MenuItem')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='menuItem',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='hello.Order'),
        ),
    ]
