# Generated by Django 2.1.4 on 2021-02-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20210227_2255'),
        ('hello', '0006_auto_20210228_0441'),
    ]

    operations = [
    ]
