# Generated by Django 2.1.4 on 2021-03-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_profile_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referralDiscount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='referral_code_used',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
